typedef int pid_t;
typedef long off_t;


extern int sys_setup(void * BIOS);
extern int sys_exit(int error_code);
extern int sys_fork();
extern int sys_read(unsigned int fd,char * buf,int count);
extern int sys_write(unsigned int fd,char * buf,int count);
extern int sys_open(const char * filename,int flag,int mode);
extern int sys_close(unsigned int fd);
extern int sys_waitpid(pid_t pid,unsigned long * stat_addr, int options);
extern int sys_creat(const char * pathname, int mode);
extern int sys_link(const char * oldname, const char * newname);
extern int sys_unlink(const char * name);
extern int sys_execve();
extern int sys_chdir(const char * filename);
extern int sys_time(long * tloc);
extern int sys_mknod(const char * filename, int mode, int dev);
extern int sys_chmod(const char * filename,int mode);
extern int sys_chown(const char * filename,int uid,int gid);
extern int sys_break();
extern int sys_stat(char * filename, struct stat * statbuf);
extern int sys_lseek(unsigned int fd,off_t offset, int origin);
extern int sys_getpid(void);
extern int sys_mount(char * dev_name, char * dir_name, int rw_flag);
extern int sys_umount(char * dev_name);
extern int sys_setuid(int uid);
extern int sys_getuid(void);
extern int sys_stime(long * tptr);
extern int sys_ptrace();
extern int sys_alarm(long seconds);
extern int sys_fstat(unsigned int fd, struct stat * statbuf);
extern int sys_pause(void);
extern int sys_utime(char * filename, struct utimbuf * times);
extern int sys_stty();
extern int sys_gtty();
extern int sys_access(const char * filename,int mode);
extern int sys_nice(long increment);
extern int sys_ftime();
extern int sys_sync(void);
extern int sys_kill(int pid,int sig);
extern int sys_rename();
extern int sys_mkdir(const char * pathname, int mode);
extern int sys_rmdir(const char * name);
extern int sys_dup(unsigned int fildes);
extern int sys_pipe(unsigned long * fildes);
extern int sys_times(struct tms * tbuf);
extern int sys_prof();
extern int sys_brk(unsigned long end_data_seg);
extern int sys_setgid(int gid);
extern int sys_getgid(void);
extern int sys_signal(int signum, long handler, long restorer);
extern int sys_geteuid(void);
extern int sys_getegid(void);
extern int sys_acct();
extern int sys_phys();
extern int sys_lock();
extern int sys_ioctl(unsigned int fd, unsigned int cmd, unsigned long arg);
extern int sys_fcntl(unsigned int fd, unsigned int cmd, unsigned long arg);
extern int sys_mpx();
extern int sys_setpgid(int pid, int pgid);
extern int sys_ulimit();
extern int sys_uname(struct utsname * name);
extern int sys_umask(int mask);
extern int sys_chroot(const char * filename);
extern int sys_ustat(int dev, struct ustat * ubuf);
extern int sys_dup2(unsigned int oldfd, unsigned int newfd);
extern int sys_getppid(void);
extern int sys_getpgrp(void);
extern int sys_setsid(void);
extern int sys_sigaction(int signum, const struct sigaction * action,struct sigaction * oldaction);
extern int sys_sgetmask();
extern int sys_ssetmask(int newmask);
extern int sys_setreuid(int ruid, int euid);
extern int sys_setregid(int rgid, int egid);
typedef int (*fn_ptr)();


